### ISSUE TITLE
configure java-relp-server-demo to listen for tls connections

### ISSUE THREAD

**Issue by kortemik** [teragrep/rlp_07#2]
java-relp-server-demo does not contain the tls functionality, however rlp_03 supports it. please configure it to provide tls on another port.

required for teragrep/rlp_05#2

**Comment by kortemik** [comment]
jla_06 has secure client configuration example
rlo_10 has secure server configuration example

**Comment by eemhu** [comment]
related PR https://github.com/teragrep/java-relp-server-demo/pull/3

**Comment by StrongestNumber9** [comment]
Seems to be merged
